---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
  namespace: NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-deploy
  template:
    metadata:
      labels:
        app: test-deploy
    spec:
      containers:
      - name: test-deploy
        image: cramirez96/jenkinstest:{BUILD_ID}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test-deploy
  namespace: NAMESPACE
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: test-deploy
